<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-9N98V8F5" failures="1" tests="4" name="Test" time="27.412" errors="0" timestamp="2025-05-16T15:37:47 GST">
  <testcase classname="testCases.TC01_User_Registration" name="Registration" time="3.889">
    <failure type="java.lang.AssertionError" message="expected [https://petstore.octoperf.com/actions/Catalog.action] but found [https://petstore.octoperf.com/actions/Account.action]">
      <![CDATA[java.lang.AssertionError: expected [https://petstore.octoperf.com/actions/Catalog.action] but found [https://petstore.octoperf.com/actions/Account.action]
at testCases.TC01_User_Registration.Registration(TC01_User_Registration.java:81)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- Registration -->
  <testcase classname="testCases.TC02_SignIn" name="Invalidcred" time="2.492"/>
  <testcase classname="testCases.TC02_SignIn" name="user_login" time="4.215"/>
  <testcase classname="testCases.TC03_AddtoCart" name="add_cart" time="3.307"/>
</testsuite> <!-- Test -->
